# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - shell: bash
        env:
          DATABASE_HOST: ${{secrets.DATABASE_NAME}}
          DATABASE_USER: ${{secrets.DATABASE_USER}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_PORT: $${{secrets.DATABASE_PORT}}
        run: |
          echo Prueba Github Actions
          echo $DATABASE_HOST
          echo $DATABASE_USER
          echo $DATABASE_PASSWORD
          echo $DATABASE_NAME
          echo $DATABASE_PORT
    #- uses: actions/checkout@v2
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
